version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: hyperchat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: hyperchat
      POSTGRES_PASSWORD: hyperchat
      POSTGRES_DB: hyperchat
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
